# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/61/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/61/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arno/Desktop/GDrive/Arno\ Deceuninck/BAHM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arno/GDrive/Arno\ Deceuninck/BAHM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/61/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/61/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/basil/ComputerGraphics/CMakeFiles /home/basil/ComputerGraphics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/basil/ComputerGraphics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mytestCGraphics

# Build rule for target.
mytestCGraphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mytestCGraphics
.PHONY : mytestCGraphics

# fast build rule for target.
mytestCGraphics/fast:
	$(MAKE) -f CMakeFiles/mytestCGraphics.dir/build.make CMakeFiles/mytestCGraphics.dir/build
.PHONY : mytestCGraphics/fast

#=============================================================================
# Target rules for targets named MakeCGraphics

# Build rule for target.
MakeCGraphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MakeCGraphics
.PHONY : MakeCGraphics

# fast build rule for target.
MakeCGraphics/fast:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/build
.PHONY : MakeCGraphics/fast

Color.o: Color.cc.o

.PHONY : Color.o

# target to build an object file
Color.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Color.cc.o
.PHONY : Color.cc.o

Color.i: Color.cc.i

.PHONY : Color.i

# target to preprocess a source file
Color.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Color.cc.i
.PHONY : Color.cc.i

Color.s: Color.cc.s

.PHONY : Color.s

# target to generate assembly for a file
Color.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Color.cc.s
.PHONY : Color.cc.s

Control.o: Control.cc.o

.PHONY : Control.o

# target to build an object file
Control.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Control.cc.o
.PHONY : Control.cc.o

Control.i: Control.cc.i

.PHONY : Control.i

# target to preprocess a source file
Control.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Control.cc.i
.PHONY : Control.cc.i

Control.s: Control.cc.s

.PHONY : Control.s

# target to generate assembly for a file
Control.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Control.cc.s
.PHONY : Control.cc.s

Intro.o: Intro.cc.o

.PHONY : Intro.o

# target to build an object file
Intro.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Intro.cc.o
.PHONY : Intro.cc.o

Intro.i: Intro.cc.i

.PHONY : Intro.i

# target to preprocess a source file
Intro.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Intro.cc.i
.PHONY : Intro.cc.i

Intro.s: Intro.cc.s

.PHONY : Intro.s

# target to generate assembly for a file
Intro.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Intro.cc.s
.PHONY : Intro.cc.s

Line2D.o: Line2D.cc.o

.PHONY : Line2D.o

# target to build an object file
Line2D.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Line2D.cc.o
.PHONY : Line2D.cc.o

Line2D.i: Line2D.cc.i

.PHONY : Line2D.i

# target to preprocess a source file
Line2D.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Line2D.cc.i
.PHONY : Line2D.cc.i

Line2D.s: Line2D.cc.s

.PHONY : Line2D.s

# target to generate assembly for a file
Line2D.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Line2D.cc.s
.PHONY : Line2D.cc.s

Point2D.o: Point2D.cc.o

.PHONY : Point2D.o

# target to build an object file
Point2D.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Point2D.cc.o
.PHONY : Point2D.cc.o

Point2D.i: Point2D.cc.i

.PHONY : Point2D.i

# target to preprocess a source file
Point2D.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Point2D.cc.i
.PHONY : Point2D.cc.i

Point2D.s: Point2D.cc.s

.PHONY : Point2D.s

# target to generate assembly for a file
Point2D.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/Point2D.cc.s
.PHONY : Point2D.cc.s

TwoDLSystem.o: TwoDLSystem.cc.o

.PHONY : TwoDLSystem.o

# target to build an object file
TwoDLSystem.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/TwoDLSystem.cc.o
.PHONY : TwoDLSystem.cc.o

TwoDLSystem.i: TwoDLSystem.cc.i

.PHONY : TwoDLSystem.i

# target to preprocess a source file
TwoDLSystem.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/TwoDLSystem.cc.i
.PHONY : TwoDLSystem.cc.i

TwoDLSystem.s: TwoDLSystem.cc.s

.PHONY : TwoDLSystem.s

# target to generate assembly for a file
TwoDLSystem.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/TwoDLSystem.cc.s
.PHONY : TwoDLSystem.cc.s

easy_image.o: easy_image.cc.o

.PHONY : easy_image.o

# target to build an object file
easy_image.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/easy_image.cc.o
.PHONY : easy_image.cc.o

easy_image.i: easy_image.cc.i

.PHONY : easy_image.i

# target to preprocess a source file
easy_image.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/easy_image.cc.i
.PHONY : easy_image.cc.i

easy_image.s: easy_image.cc.s

.PHONY : easy_image.s

# target to generate assembly for a file
easy_image.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/easy_image.cc.s
.PHONY : easy_image.cc.s

engine.o: engine.cc.o

.PHONY : engine.o

# target to build an object file
engine.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/engine.cc.o
.PHONY : engine.cc.o

engine.i: engine.cc.i

.PHONY : engine.i

# target to preprocess a source file
engine.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/engine.cc.i
.PHONY : engine.cc.i

engine.s: engine.cc.s

.PHONY : engine.s

# target to generate assembly for a file
engine.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/engine.cc.s
.PHONY : engine.cc.s

ini_configuration.o: ini_configuration.cc.o

.PHONY : ini_configuration.o

# target to build an object file
ini_configuration.cc.o:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/ini_configuration.cc.o
.PHONY : ini_configuration.cc.o

ini_configuration.i: ini_configuration.cc.i

.PHONY : ini_configuration.i

# target to preprocess a source file
ini_configuration.cc.i:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/ini_configuration.cc.i
.PHONY : ini_configuration.cc.i

ini_configuration.s: ini_configuration.cc.s

.PHONY : ini_configuration.s

# target to generate assembly for a file
ini_configuration.cc.s:
	$(MAKE) -f CMakeFiles/MakeCGraphics.dir/build.make CMakeFiles/MakeCGraphics.dir/ini_configuration.cc.s
.PHONY : ini_configuration.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mytestCGraphics"
	@echo "... MakeCGraphics"
	@echo "... Color.o"
	@echo "... Color.i"
	@echo "... Color.s"
	@echo "... Control.o"
	@echo "... Control.i"
	@echo "... Control.s"
	@echo "... Intro.o"
	@echo "... Intro.i"
	@echo "... Intro.s"
	@echo "... Line2D.o"
	@echo "... Line2D.i"
	@echo "... Line2D.s"
	@echo "... Point2D.o"
	@echo "... Point2D.i"
	@echo "... Point2D.s"
	@echo "... TwoDLSystem.o"
	@echo "... TwoDLSystem.i"
	@echo "... TwoDLSystem.s"
	@echo "... easy_image.o"
	@echo "... easy_image.i"
	@echo "... easy_image.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... ini_configuration.o"
	@echo "... ini_configuration.i"
	@echo "... ini_configuration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

